//
// Created by root on 19-3-17.
//

#ifndef FTP_SERVER_CONFIG_HPP
#define FTP_SERVER_CONFIG_HPP

#define DEFAULT_THREAD_CNT_OF_THREAD_POOL 128
#define THREAD_POOL_MAX_TASK_CNT 10240
#define FTP_MAX_USER_ONLINE_CNT 10200
#define LOGIN_FAIL_DELAY_SEC 3

#define MAX_FD_CNT 1024000

#define DEFAULT_BACKLOG 20
#define FTP_CMD_CONNECTION_BACKLOG 10240
#define FTP_DATA_CONNECTION_BACKLOG 5

#endif //FTP_SERVER_CONFIG_HPP
